### ISSUE TITLE
Add hreflangs?

### ISSUE THREAD

**Issue by mbinet** [marcelofinamorvieira/next.js-i18n-blog-demo-site-search-fork#2]
Hey team.

I noticed this demo didn't come with hreflangs. It might be a good addition as articles are translated.

I am going to add these for a client's website anyway.
I'd be happy to create a PR here if you're up for it.

**Comment by matjack1** [comment]
hey @mbinet sure! Thank you very much! Feel free to open a PR whenever you have something and we'll surely check it. I'm closing this for now, whenever you want, just open the PR, no problem!
